
sudo: required
dist: trusty
language: cpp

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make

before_script:
  - curl -O -O boost.tar.gz http://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.gz/download
  - tar xzvf boost.tar.gz
  - cd boost
  - sudo apt-get update
  - sudo apt-get install build-essential g++ python-dev autotools-dev libicu-dev build-essential libbz2-dev libboost-all-dev
  - ./bootstrap.sh --prefix=/usr/local
  - sudo ./b2 install

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - clang-3.7
    - libboost-all-dev
    - cmake

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
